[package]
name = "ondrop"
version = "0.1.0"
authors = ["Peter Todd <pete@petertodd.org>"]
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/petertodd/ondrop"
description = "Do something on drop."

[dev-dependencies]
dropcheck = "0.1.1"
